### ISSUE TITLE
Docs improvement: Getting started with fixtures

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#5] opened 2015-11-07 10:22 UTC
I'm trying to understand, how to implement the most simple fixture in Afterglow. I have my-show.clj, which is copy-paste from your latest README.md example file.

I'm stuck on the line "  ;; TODO: Replace this to patch in an actual fixture in your show".

**First try.** Copy-paste from https://github.com/brunchboy/afterglow/blob/master/src/afterglow/examples.clj

```
  (show/patch-fixture! :torrent-1 (blizzard/torrent-f3) universe 1
                       :x (tf/inches 44) :y (tf/inches 51.75) :z (tf/inches -4.75)
                       :y-rotation (tf/degrees 0))
```

Not working :( 

```
java.lang.RuntimeException: No such namespace: adj, compiling:(/Users/dandaka/projects/lights/my-show.clj:43:33)
```

**Second try.** Reading the docs https://github.com/brunchboy/afterglow/blob/master/doc/fixture_definitions.adoc

Doesn't help at all, because almost no examples there. I have big troubles with Closure syntax right now. And there is no "simple and working code to copy-paste" to experiment on.

**Third try.** File https://github.com/brunchboy/afterglow/blob/master/src/afterglow/fixtures.clj#L65

Same story, can't copy-paste and modify. No idea, what is that exactly.

**What would be cool to see.** Simplest fixtures to work with. For example, I have RGB LED light on universe 1 on 1,2,3 DMX channels. If I could copy-paste code needed for them to work, it would save lots of time for newbee users like me.

Thank you :+1:

**Comment by brunchboy** [comment] 2015-11-07 21:19
I think part of the problem is you are being forced to learn very many complicated things at the same time, so let’s try to break them into pieces. One of the things it sounds like you are trying to do is write a fixture definition to tell Afterglow how to control a light that you actually have, so let’s define that. Is the manual for the light online anywhere? And if you don’t mind, let’s move this discussion to the [Wiki section](https://github.com/brunchboy/afterglow/wiki/Questions#defining-fixtures) that I created for this purpose. Please jump there and see if I am on the right track?

Also, as noted in that section, if your light is one of the many that already has a fixture definition for it in the QLC+ lighting control package, Afterglow can translate that fixture definition into its own Clojure format for you.

**Comment by brunchboy** [comment] 2015-11-07 21:33
I am puzzled by the error message you cite above, though, could you paste in the whole stack trace, and perhaps the version of your `my-show.clj` which caused it to occur? It is complaining about being unable to find the namespace `adj`, which is confusing because I don’t see anything that would try to refer to it. Other fixture definitions in my original `examples` namespace did use `adj` to refer to lights from American DJ. The copy-paste line you used references the `blizzard` namespace, which is in fact aliased by the `ns` form at the start of `my-show.clj`, at least as it existed in the `README`:

```clojure
(ns my-show
  "Set up the fixtures, effects, and cues I actually want to use."
  ;; TODO: Your list of required namespaces will differ from this, depending on
  ;;       what fixtures you actually use, and what effects and cues you create.
  (:require [afterglow.core :as core]
            ;; lots omitted...
            [afterglow.fixtures.blizzard :as blizzard]
            ;; more omitted...
            [taoensso.timbre :as timbre]))
```

**Comment by brunchboy** [comment] 2015-11-07 21:39
As far as examples of things to try and examples to edit, it might be worth spending a little time just getting more comfortable with Clojure expressions, functions, and concepts on their own. If it is your first Lisp, the initial learning curve can be quite steep! But so worth it. :smile: The [Try Clojure](http://www.tryclj.com) interactive site is a quick way, although you may already be past that; if you do experiment with it, note that you do need to press <kbd>Enter</kbd> or <kbd>Return</kbd> after each line on that site for it to process your input. It also has links to other documentation and resources.

What are you using as your editor and REPL environment?

**Comment by dandaka** [comment] 2015-11-08 11:26
1. Don't mind moving discussion anywhere. I just don't see any way to ask/reply/comment on Wiki. So if you don't mind, I will continue here. You can always close this ticket or mark it "discussion" or something.

2. My project is here
https://github.com/dandaka/lights-experiment

my-show.clj is here
https://github.com/dandaka/lights-experiment/blob/master/my-show.clj

Log is here:
https://gist.github.com/dandaka/b9d9aec8540ab402c21e

3. Yes, I'm trying to learn many things at the same time — no choice :) But it doesn't change requirements for a good documentation for a newbee users. My point is to add few copy-paste examples, so a user can learn these "many complicated things" on a working system (even at a basic level).

4. You've guessed configuration of my light exactly right — RGB on 1,2,3. Nothing else on it.

5. There is no need to include all (or even many) fixture configurations in examples. But few basic configurations are a must to have. Users need to copy-paste and see them working. After you got the system working, you can fine tune and learn other concepts.

6. I got your point about QLC+ and converter from one format to another, but it adds another complexity level. On my machine it is not working correctly. And I guess your config is 100% right in my case.

7. Sure I will learn Closure, but first I need to see your system working and get hands-on experience with its possibilities. If there is not enough value, I could jump to something else. If it delivers value, I have motivation to invest time learning Clojure and other stuff.

8. My editor is Sublime Text 3 + SublimeREPL. Again, it is not very important at the moment, since I can't get anything working. It seems, that it makes sense, when you have working system and can code.

Thank you for your time :+1:

**Comment by brunchboy** [comment] 2015-11-09 05:00
That all makes sense, and you are helping write that level of beginner documentation right here, which I appreciate!

So where do things stand now? That error log gist you posted seems to be from an earlier problem, the bad `:refer` that I fixed in Issue #4 and not the `adj` namespace that you mentioned here. But thank you for pointing me at your project! I have cloned it and can try reproducing things that way.

All right, I think I see some issues I can help you with, I will fork your project and submit a pull request. You have a file `my-show.clj` which is organized for working with Afterglow as a standalone jar file, but at this early stage of exploration it is probably a lot more convenient to work with it in the REPL, so I am going to move that into your source hierarchy, and fix some of the includes. (For example, your fixture definition is referring to a namespace `chan` which has not been loaded by the `:require` statement in the opening `ns` form.)

I will also change your `project.clj` so that when you run it interactively via `lein repl` it starts you out in the `lights.my-show` namespace, to make it easy to get started experimenting with functions in that file, and I will copy in a few functions from my own `example.clj` namespace to work with. And another person who has been working with Afterglow ran into an issue with some of the dependencies, so I will update the project to use a more recent snapshot of Afterglow which hopefully will save you from running into the same problem.

Ok! With the tweaks I am about to submit as a pull request, I can start your project using `lein repl` and then evaluate the following two statements, and I see channels 1 and 2 (the red and green channels for your light) get set to 255 and 165 in OLA:

```clojure
(show/start!)
(show/add-effect! :color (global-color-effect "orange"))
```

See if you can get that same result, and hopefully start setting your light to different colors and seeing it actually do it for you! Then we can play with fades and other fancier things.

**Comment by brunchboy** [comment] 2015-11-09 05:07
Oh, also, in response to a few of your other points: Yes, we can keep the conversation here if it is easier for you; it is definitely better structured for back-and-forth questions than the Wiki, but once we are all done, either one of us can edit the Wiki to include some of the useful conclusions and advice that come out of this exercise.

And it is also entirely possible that Afterglow is not the best option for what you are trying to do; if it turns out that there are other systems which are more finished, or more readily adapted to your needs, it won’t hurt my feelings, I am grateful to you for trying it, and happy to help in any way I can while you evaluate it. Thanks for your feedback to help make it better. Either way I would be curious to know what it is you are trying to build!

**Comment by dandaka** [comment] 2015-11-13 19:03
Dear @brunchboy, I need some help explaining why this line is not working:

https://github.com/dandaka/lights-experiment/blob/master/src/lights/my_show.clj#L66

Can't get to understand, what "rgb-1" means here —

https://github.com/dandaka/lights-experiment/blob/master/src/lights/my_show.clj#L63

And can't find any meaningful (for my newbee mind) docs on ```patch/fixture!``` function.

**Comment by brunchboy** [comment] 2015-11-13 20:47
I have just a few minutes between meetings, but I wanted to write a quick initial reply to hopefully help you get further, or at least collect more information. My initial reflex was to say that the way to find the documentation for a Clojure function is like this:

```clojure
(doc show/patch-fixture!)
```
 in the REPL, and that you can look at the Afterglow API docs online, for example [show/patch-fixture!](http://deepsymmetry.org/afterglow/doc/afterglow.show.html#var-patch-fixture.21)…

But then I noticed that you are right, the documentation for `patch-fixture!` is pretty useless to someone who doesn’t already know what it does, never mind whether you are new to Clojure or not. So I will definitely fix that, I wrote that function before I decided to embark on a serious documentation effort, and never got back to it. Thanks for pointing it out!

To answer your immediate question, the `key` argument, e.g. `:rgb-1` or `:head-1` in your examples, is a keyword used to identify that fixture within the show. So if you patch another fixture under the same keyword, it will replace it. And if you call `(show/fixtures-named :rgb)` it will return the fixture you created as `:rgb-1`, along with any other fixture whose key is of the form "rgb-" plus a number.

What do you mean when you say your line is “not working“? I did not see anything obviously wrong with it but have not had time to study it in depth.

**Comment by brunchboy** [comment] 2015-11-14 06:12
All right, I have beefed up the `patch-fixture!` documentation in c2a4902d2f491df82e18c006384663caa4c69fa3. Can you elaborate about what isn’t working about https://github.com/dandaka/lights-experiment/blob/master/src/lights/my_show.clj#L63 for you? Are you getting an exception, or is something just not behaving the way you expect? Hold on, I’ll try pulling your changes and running it myself…

Ok, you are getting an exception in `(use-my-show)` because something is trying to parse a keyword as an integer. It’s a little hard to tell exactly why, because you are calling `(use-my-show)` at the top level in that namespace, so it fails while trying to load the namespace, and that makes it impossible to test the functions defined in the namespace on their own. I commented out that line so I could at least launch the repl and load the `my-show` namespace. Having done that, I can call `(head280)` and see what it returns:

```clojure
lights.my-show=> (clojure.pprint/pprint (head280))
{:channels
 [{:offset 1,
   :type :tilt,
   :functions
   [{:start 0,
     :end 255,
     :range :variable,
     :type :tilt,
     :label "Tilt",
     :var-label "Tilt"}],
   :fine-offset :tilt}
  {:offset 2,
   :type :pan,
   :functions
   [{:start 0,
     :end 255,
     :range :variable,
     :type :pan,
     :label "Pan",
     :var-label "Pan"}],
   :fine-offset :pan}
  {:offset :shutter,
   :type nil,
   :functions
   [{:start 0,
     :range :fixed,
     :type :shutter-closed,
     :label "shutter-closed",
     :end 31}
    {:start 32,
     :range :fixed,
     :type :shutter-open,
     :label "shutter-open",
     :end 255}]}
  {:offset 11,
   :type :dimmer,
   :functions
   [{:start 0,
     :end 255,
     :range :variable,
     :type :dimmer,
     :label "Dimmer"}]}],
 :name "Head PHS 280"}
```

Scanning that, I can see the problem: Your shutter channel is mal-formed, it has an `:offset` value of `:shutter`, and `patch-fixture!` is trying to parse that as a relative channel address (an integer), and  blowing up. And that's because `chan/functions` expects the function keyword _before_ the channel offset. Your line:

```clojure
(chan/functions 10 :shutter 0 "shutter-closed" 32 "shutter-open")
```

should be:

```clojure
(chan/functions :shutter 10 0 "shutter-closed" 32 "shutter-open")
```

But fixing that wasn’t enough; the shutter channel now looks fine to me but I am still getting the same error… so let’s look back at the fixture definition map again. Whoops! I see two other problems. Your pan and tilt channels have `:fine-offset` values (low-byte channels) assigned to them, but instead of being integers, those are set to `:pan` and `:tilt`, which cause the same integer parse error. (You can look at the stack traces associated with these errors by typing `*e` in the repl, but it takes some practice to learn to read Clojure stack dumps.) To fix this problem, just drop the extra parameters. In other words, your lines:

```clojure
(chan/tilt 1 :tilt)
(chan/pan 2 :pan)
```

should be just:

```clojure
(chan/tilt 1)
(chan/pan 2)
```

Once I made those two other changes, I was able to run `lein repl` and then call `(use-my-show)` with no exception. I will make another pull request in case you want to just jump to that point. (I will leave `(use-my-show)` commented out because it’s probably best to call it manually while you are working on and debugging your fixture definitions.

> If you actually do have two-byte pan and tilt values, like many fixtures do, list the low-byte channel offset after the high-byte channel offset in your `chan/tilt` and `chan/pan` calls.

Anyway,  you are a lot further along than you were last weekend!

**Comment by brunchboy** [comment] 2015-11-14 06:47
So after writing this I was thinking that it would be a lot friendlier if the fixture definition functions would validate their arguments and fail right away if you tried to create a channel with a non-integer offset or fine offset. And I know how to do that now, with precondition annotations in Clojure function definitions; when I was first writing Afterglow I hadn’t learned how to use those. I went and looked at my source, planning to add them… and I discovered I had tried to do that already, but I had messed up, forgetting to group all the precondition predicates in a vector! So it was compiling fine, but the map was not being properly interpreted by Clojure. I have fixed that in 37220c733da9a6bba33954d43b9dc52d75727b5a, and pushed a new snapshot of Afterglow. Since your project is depending on the snapshot builds, from now on if there are similar problems with a fixture definition, it will fail to create, giving you a stack-trace reporting that the offset must be an integer.

```clojure
#error {
 :cause Assert failed: (integer? offset)
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message java.lang.AssertionError: Assert failed: (integer? offset), compiling:(lights/my_show.clj:72:1)
   :at [clojure.lang.Compiler load Compiler.java 7239]}
  {:type java.lang.AssertionError
   :message Assert failed: (integer? offset)
   :at [afterglow.channels$functions doInvoke channels.clj 213]}]
 :trace
 [[afterglow.channels$functions doInvoke channels.clj 213]
  [clojure.lang.RestFn invoke RestFn.java 521]
  [lights.my_show$head280 invoke my_show.clj 41]
  [lights.my_show$use_my_show invoke my_show.clj 66]
  [lights.my_show$eval350 invoke my_show.clj 72]
…
  [clojure.main main main.java 37]]}
```

So hopefully that will be less cryptic for you, me, and everyone else in the future. (Although, as I said earlier, it takes a while to learn how to read Clojure stack traces. :grimacing: )

**Comment by brunchboy** [comment] 2015-11-14 23:33
After a little bit of Google research, it looks like you are working on a definition for the Futurelight PHS 280, and I found a spreadsheet that documents its DMX channels. If I found the correct fixture, there are indeed, low-byte pan and tilt channels at offsets 15 and 16, so you will want to update your definition to take advantage of them. If I have the correct light, though (and the spreadsheet is right), it seems you have the pan and tilt channels reversed, so it should be:

```clojure
(chan/pan 1 15)
(chan/tilt 2 16)
```

Also, as things stand in your definition so far, Afterglow thinks that the entire range of values from 32 to 255 in the shutter channel (10) means “shutter open” when there are a bunch of other ranges in there for strobe and pulse effects. So until you get those added, when you want to create an effect to open the shutter, be sure to stick to the beginning of the range. Here is one that would do that for all fixtures with a “shutter-open” function:

```clojure
(show/add-effect! :shutter-open
  (afterglow.effects.channel/function-effect "Shutters open" :shutter-open 0
                                             (show/all-fixtures)))
```

You might want to require `afterglow.effects.channel` (I often do so `:as chan-fx`) to save typing that long namespace.

I will just leave these as a comment rather than a pull request, because I may be totally wrong about the fixture you have. :smile:

**Comment by dandaka** [comment] 2015-11-18 16:12
So far works fine! I have lost access to heads, so them aren't actual at the moment.

But I have question regarding LED PARs. One of them has only 3 channels (RGB), no dimmer.

Is it possible to use this PAR with your dimmer effects?

PS. Sorry, that I can't answer all of your questions. My time with these lights is pretty limited and I have to make maximum progress at a given time. Really appreciate your help with getting started and promise to contribute with max feedback I have.

**Comment by brunchboy** [comment] 2015-11-18 17:58
Dimmer effects will only affect actual dimmer channels, as you suspected, so no, they will have no effect on your LED PAR which lacks a separate dimmer channel. However, that is not a big problem: There is nothing special about dimmer effects, and you can achieve precisely the same result using a color effect, with a variable parameter which varies the lightness value (0 is fully black, 50 is fully bright version of the hue and saturation, and as you go above 50 towards 100, the hue gets bleached towards white).

To experiment conveniently with this, I suggest using a show variable, something like this:

```clojure
(show/set-variable! :lightness-level 50)
(show/add-effect! :color (global-color-effect
  (params/build-color-param :h 60 :s 100 :l :lightness-level)))
```

This assigns an orange color (hue 60) to all of your lights, and the lightness of that color starts out at maximum brightness, fully saturated. To dim it by half you need simply change the value of the show variable `lightness-level` like so:

```clojure
(show/set-variable! :lightness-level 50)
```

And you should immediately see the lights dim. You can also use an oscillated parameter to make the lightness vary over time synced to the show metronome, and all the other things you would be able to do with a dimmer effect. If you prefer to initially set the colors using RGB values rather than HSL, you can do so like this:

```clojure
(show/add-effect! :color (global-color-effect
  (params/build-color-param :r 255 :g 255 :b 0 :l :lightness-level)))
```

and `build-color-param` will first calculate the color based on the RGB values, and then adjust them as needed by the lightness level you chose.

**Comment by dandaka** [comment] 2015-11-20 06:29
So far system works perfect :+1:

1) I would be grateful for some examples of how to create cues (or links to such), since I can't find any of them. 

https://github.com/brunchboy/afterglow/blob/master/doc/cues.adoc
https://github.com/brunchboy/afterglow/tree/master/doc
https://github.com/brunchboy/afterglow/
— no luck

2) How to group fixtures? And assign to selected groups some effects?

**Comment by brunchboy** [comment] 2015-11-20 21:39
I am glad it is working for you, apart from what sounds like a limitation with the MIDI environment. The best place to look for examples of creating cues is in the [examples namespace](https://github.com/brunchboy/afterglow/blob/master/src/afterglow/examples.clj). The [make cues](https://github.com/brunchboy/afterglow/blob/master/src/afterglow/examples.clj#L349) function creates a bunch of cues which do various kinds of things. Try and figure out how they do what they do, by digging in to the API docs of the functions they use, as well as the documents you listed above. Then you can modify ones that look promising to work with the fixtures that you actually have.

You group fixtures however you want. When you are creating an effect (including within a cue), you pass the effect the list of fixtures that you want it to affect. You can use any Clojure code you want to build that list; as I noted way up this thread, the function `show/fixtures-named` can be a good starting point to find a fixture or a group of fixtures with the same name (optionally followed by a dash and number). You can use the standard Clojure `concat` function to combine groups, although it would probably be best to use sets and [set-manipulation functions](http://clojuredocs.org/clojure.set) to make sure you don’t end up including the same fixture more than once.

I don’t know how one would sync with Quil or Overtone (I don’t even know what the former is). I have not checked whether Overtone can be configured to send MIDI clock pulses based on its tempo. The great thing about Overtone, though, is that you can add your own code, right? Then it could sync in an even deeper way, since its metronomes were the basis of my own. I have written implementations to sync to MIDI clock, to a user tapping out the tempo on a MIDI controller or the web UI (which you could use in a worst-case scenario), as well as Traktor and Pioneer pro DJ gear. You can look at the source of those implementations as a basis for syncing with something else, too.

**Comment by dandaka** [comment] 2015-11-29 12:23
Can't find any example with one channel split into a few functions. I have a PAR which has dimmer/strobe on a single DMX channel. My take on definition looks like this:

https://github.com/dandaka/lights-experiment/blob/master/src/lights/my_show.clj#L33

What I was expecting:
1. I am defining fixture with two ranges on a single DMX channel — one for dimmer, second for strobe functions
2. I use global effects of dimmer/strobe to work with this specific device

How it works now:
1. So far it doesn't work as intended. Whole channel's range 0-255 is used for dimming.
2. When I specify ```(show/add-effect! :dimmers (global-dimmer-effect 230))```, it is not translated to ```230/255*189=179``` for this fixture

I think my definition is wrong, but can't figure any examples.

I was thinking I should use ```(chan/functions :type :control)```, but when used I lost dimmer functions too.

Is there anything I'm missing?

**Comment by brunchboy** [comment] 2015-11-29 16:07
I’m afraid I’m traveling so can’t look in as much depth as sometimes, but it looks like you are close. It seems like you might be confusing the input and output formats of `chan/functions`. The examples of using it can be found in my own fixture definitions, for example for the Blizzard [Torrent F3](https://github.com/brunchboy/afterglow/blob/master/src/afterglow/fixtures/blizzard.clj#L117) (ignore the `:scale-fn` stuff for now though). Hopefully between that, and the other function channel specifications before and after it, you can see examples of what you are trying to do. Otherwise, I could take a stab at fixing your definitions later next week.

**Comment by dandaka** [comment] 2015-11-30 08:23
I have checked all examples, but still many things are puzzling me. Simple examples are what works best in getting started.

1. If my fixture DMX channel is split in two types (dimmer and strobe), why do I have to specify "main" (like ```chan/functions :main-key```) purpose. If there is no "main" purpose, why do I need to config it that way? Since I will tell Afterglow afterwards about specific DMX values and their meaning... Is it kind of a shortcut? 

2. Maybe I'm confusing input/output. I get it like this
— I have 4th channel on my fixture
— I have to tell Afterglow, that it is actually controls two different functions: dimmer (up to 189 value) and strobe (190+)

After I do this correctly, I will have native Afterglow dimmer and strobe functions working correctly. Like I'm setting dimmer to 100% for all fixtures, and this specific one gets 189 DMX value.

**Comment by brunchboy** [comment] 2015-11-30 16:02
Yes, simple examples would be great! I would really appreciate it if you would write some when you figure this out, and we can include them in the documentation. The first keyword argument to `chan-functions` is intended to describe the overall channel type, and is really only used as documentation now that function ranges are where behavior is found. In a sense it is a legacy from the evolution of the data structure. So you can put anything you want there, `:control` is a generic channel type that I have used in similar situations. Or `:shutter` might be a reasonable description of your channel. So something like this might achieve what you need:

```clojure
(chan/functions :shutter 4
                0 :dimmer
                190 :strobe)
```

That set of inputs (arguments) to the `chan/functions` function produces the following channel map when you are building your fixture:

```
{:offset 4,
 :type :shutter,
 :functions
 [{:start 0,
   :range :variable,
   :type :dimmer,
   :label "Dimmer",
   :end 189}
  {:start 190,
   :range :variable,
   :type :strobe,
   :label "Strobe",
   :end 255}]}
```

I can’t really test this until I am back home later in the week though.

**Comment by brunchboy** [comment] 2015-11-30 16:12
And now that I think about it, dimmer effects may not currently support fixtures which only use part of the DMX range for the dimmer. That is a really weird design choice; even 256 dimmer values is considered too few by today’s high-end lights. So I think that in order to support this fixture, we are going to have to add some complexity to the dimmer effect implementation itself, which would slow down effects for more normal fixtures too.

Yes, a quick look at `src/afterglow/effects/dimmer.clj` [confirms this](https://github.com/brunchboy/afterglow/blob/master/src/afterglow/effects/dimmer.clj#L47-L50). It is designed to work with channels that are wholly dedicated to dimming, and the channel `:type` value is more than documentation, it must be `:dimmer` for dimmer channels, and must *not* be `:dimmer` for weird channels like yours which are only partially used for dimming. So it may be that your more complicated fixture definition is already correct (although putting the `:end` values in your maps is meaningless, `chan/functions` will replace them). But to work with that kind of channel, you need to use a [function effect](https://github.com/brunchboy/afterglow/blob/master/doc/effects.adoc#function-effects), not a dimmer effect, and you need to make sure that the channel type is not `:dimmer` so that dimmer effects do not mess with it.

**Comment by brunchboy** [comment] 2015-12-04 04:31
I’m back! Have you had any luck trying to use function effects rather than dimmer effects with this light? I have thought a little bit about ways to enable dimmer effects to use function ranges, but there are complications, and I am not happy with any of the answers yet. Have you explored the code any, and do you have any ideas of your own? I am also not entirely happy with just telling people to use function effects for such lights, because then you lose the ability to scale dimmer values using masters… but unless there are a lot of such lights out there, this may not be worth dealing with. Who manufactures this light, and what is its model? I would like to learn more about it.

**Comment by dandaka** [comment] 2015-12-04 09:46
Since some of my lights don't have dimmer channel anyways, I don't see this outcome as a limitation right now. Just had to figure out, why it is not working. Need to find some time on this weekend to experiment, will get back after it :)

**Comment by brunchboy** [comment] 2015-12-04 15:44
Ok! But sleeping on the question, after looking at the code yesterday, I have come up with a good solution, so I expect to have a new snapshot release for you early this weekend that will let you use a dimmer effect with both kinds of lights, and will emit function assigners for lights like this one, and ordinary channel assigners for more standard dimmer channels, without affecting performance for the traditional lights.

**Comment by dandaka** [comment] 2015-12-04 15:46
Sound fantastic!

**Comment by brunchboy** [comment] 2015-12-05 07:38
All right, I just pushed a new `0.1.6-SNAPSHOT` in which dimmer effects can work with both standard dimmer channels and multipurpose channels with a `:dimmer` function range.

**Comment by dandaka** [comment] 2015-12-06 15:03
Works like charm!

**Comment by brunchboy** [comment] 2015-12-06 21:09
Great! It’s a much more meaningful test when you have an actual fixture than when I fake one and watch the DMX output. :grin:

**Closed** 2016-03-27 06:45 UTC
Labels: help wanted
