### ISSUE TITLE
MIDI messages not received (beyond channel 1?)

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#8] opened 2015-11-20 15:58 UTC
1) I have an active MIDI over Network session

2) I have physical connection to a MIDI controller (Traktor Kontrol Z1)

3) When I use knobs on Traktor Kontrol Z1, which are using channel 1, I can detect them with ```(afterglow.midi/identify-mapping)```

```
lights.my-show=> (afterglow.midi/identify-mapping)
(afterglow.midi/identify-mapping)
{:command :control-change, :channel 0, :note 1, :velocity 55, :device {:name "Traktor Kontrol Z1 Input", :description "Traktor Kontrol Z1 Input"}}
```

4) When I use other knobs, that are using channel 2, they aren't detected with Afterglow

```
lights.my-show=> (afterglow.midi/identify-mapping)
(afterglow.midi/identify-mapping)
nil
```

5) I can see them coming http://take.ms/VRD9x

6) I have changed midi-net messages to channel 1, and they are detected with Afterglow (no restart)

```
lights.my-show=> (afterglow.midi/identify-mapping)
(afterglow.midi/identify-mapping)
{:command :control-change, :channel 0, :note 1, :velocity 105, :device {:name "midi-net", :description "Network midi-net"}}
```

**Comment by brunchboy** [comment] 2015-11-20 20:59
Afterglow doesn’t filter by channel, and I double-checked the source code to confirm that, so it sounds like the problem is happening at a lower layer in the Java MIDI system. Afterglow uses Overtone’s [midi.clj](https://github.com/overtone/midi-clj) to interface with Java MIDI, and uses the [midi-handle-events](https://github.com/overtone/midi-clj/blob/master/src/overtone/midi.clj#L222-L244) function to get notified whenever a given device sends MIDI messages. If you can put together a snippet of code using this function which successfully reports the messages coming in on the other channels, even though Afterglow cannot see them, then it is an issue with Afterglow, and I will have to dig deeper. Otherwise an issue needs to be opened with midi-clj.

**Comment by dandaka** [comment] 2015-11-22 16:30
Dear James,

I have installed Overtone and used ```(event-debug-on)``` to monitor MIDI messages. Works fine with their library, but not works with Afterglow.

I include log for both programs running at the same time:
Overtone — https://gist.github.com/dandaka/29e06415b2baf43b06c3
Afterglow — https://gist.github.com/dandaka/815b459f695d6e1b4535

Also src for my project, if you need it in any case https://github.com/dandaka/lights-experiment/blob/master/src/lights/my_show.clj

Anything I can help to find the source of this issue?

**Comment by brunchboy** [comment] 2015-11-22 21:01
Vlad, thanks for digging further into this. I wonder if there are any logs (in REPL buffers, or the Afterglow log file) showing anything? As things stand, I am completely baffled about what might be happening. Trying to use the Overtone `midi-handle-events` function directly within your Afterglow environment would help us find out if the problem is indeed happening at their level, so we could open an issue with them.

I am going to try to find some time to use the Native Instruments Controller Editor to change some controls on my Traktor Kontrol F1 to use different channels, and see if I can reproduce the problem. If I can’t, I’m not sure what I will be able to do. But since I will be traveling for a week in a few days, I’m not sure when I will be able to get to this if I can’t today. Fingers crossed… Otherwise I could also send you some code to try in your Afterglow environment.

**Comment by brunchboy** [comment] 2015-11-22 21:27
All right, excellent news, I have been able to reproduce the problem with my Kontrol F1, which will make it *much* easier to figure out. And I have already confirmed that I am getting the MIDI events from Overtone’s library, so they are indeed getting lost somewhere in Afterglow. Now I just need to figure out how I managed to screw this up. :blush:

**Comment by brunchboy** [comment] 2015-11-22 22:29
OK, figured it out! It turns out not to have anything to do with the channels, actually, or at least not directly. For whatever reason, the Native Instruments controllers send MIDI messages which result in the Overtone MIDI library creating slightly different Clojure maps to represent them. I was previously always looking in the `:status` key of the map in order to figure out what kind of MIDI message it was, which works fine for the Ableton Push, but with the Kontrol F1, the `:status` key was `nil` for `control-change` messages, and so they were not getting processed.

I just committed a change to always look in the `:command` key for command-type messages, and in the `:status` key only for status-type messages, and I can now identify mappings both from my Push and Kontrol F1, regardless of what channel those are assigned to.

I’ve pushed a new build of afterglow-0.1.5-SNAPSHOT. Do a `lein clean` followed by a `lein -U deps` to make sure you have it, and see if this fix works for you when you have a chance. If so, we can close this issue.

Thanks for reporting it and helping track it down, this is why having multiple users is helpful!

**Comment by dandaka** [comment] 2015-11-23 04:43
Works fine now, thank you!

**Comment by brunchboy** [comment] 2015-11-23 04:45
Awesome! Thanks for letting me know. I will close this issue. I want to release version 0.1.5 in the next couple of days, there are enough important new features and fixes in there to get it out for people who are not using snapshots. I just want to add a few more tests and polish a couple of things first.

**Closed by brunchboy** 2015-11-23 04:45 UTC
