### ISSUE TITLE
More oscillators?

### ISSUE THREAD

**Issue by dandaka** [brunchboy/afterglow#9] opened 2015-12-04 16:12 UTC
I'm thinking about using oscillators with user input and MIDI input. General idea is to mix, say, sine-generated values with sound intensity. One simple way is to achieve this is to use `:max` parameter of `(afterglow.effects.params/build-oscillated-param oscillator)`.

But music/show has another dimension — time, which is interesting to use.

I'm thinking about this kind of oscillators:

![osc](https://cloud.githubusercontent.com/assets/2384694/11594364/40c099c2-9ab2-11e5-9769-4df3a7ebb16e.png)

The third one is a bit tricky to design. I have showed 0.5x beat case. To use floats in this case ("make me a sine every 0.4 beat) Afterglow has to "collect" them.

What do you think of it? Are this types achievable with current Afterglow?

**Comment by dandaka** [comment] 2015-12-04 16:21
Another idea is to implement same logic to sine oscillators also.

**Comment by brunchboy** [comment] 2015-12-04 16:26
Indeed. The current oscillators can’t produce waveforms like this (other than the top one, which is an ordinary sawtooth oscillator), but if you look at the source code, they are pretty simple, and you could use them as the basis for creating ones that work exactly the way you want.

As far as working with sound intensity, I am definitely interested in building a system that captures sound input, uses Fourier transforms to identify intensity at various frequency bands, and then drives visualizations and effects based on that. I haven’t gotten around to it yet, perhaps you could get that started before I do!

**Comment by dandaka** [comment] 2015-12-04 16:29
Ok. Will try one day to figure them out :)

I'm use level analyzers on Ableton side (via a VST plugin pizmidi AudioToCC) to transform levels to MIDI CCs (4 at the moment). The goal is to create sound-reactive show with lights and vizualization based on sound levels. Hope to record some videos with result later in December and share with you for inspiration.

**Comment by brunchboy** [comment] 2015-12-04 16:36
That sounds awesome, I can’t wait to see what you come up with!

I also thought of another way you can create patterns like the lower two waveforms in your illustration with the current code: You can use a [chase](https://github.com/brunchboy/afterglow/blob/master/doc/effects.adoc#chases), which alternates back and forth between an oscillator which is running all the time, and a [blank effect](https://github.com/brunchboy/afterglow/blob/master/doc/effects.adoc#blank-effects) which is doing nothing. (You could use a square wave oscillator to control which scene in the chase is currently active.) Chases are a new (but important) feature, so you might have not seen them when you initially looked through the documentation. If it would help I could try to put together an example of how to use one to create your diagrams this weekend. If you do want to experiment with these, make sure you have updated your project to depend on the latest snapshots, `[afterglow "0.1.6-SNAPSHOT"]`.

**Comment by dandaka** [comment] 2015-12-04 16:39
Would be great, otherwise it will take years with my current speed :)

**Comment by brunchboy** [comment] 2015-12-06 00:09
All right, I have added an example to [graphterglow](https://github.com/brunchboy/graphterglow/commits/master) that creates this kind of a pattern using a chase. The code there is a bit more complex because it has to support drawing the graph, which looks like this:

![sawgap](https://cloud.githubusercontent.com/assets/2228869/11610898/bc98fdda-9b77-11e5-8615-ab0c1ce7737a.png)

So here is just the code to create a chase which drives a dimmer as shown in that graph, and add it to a show. I wasn’t sure about exactly what timing you meant from your own graphs, so this one has a sawtooth wave that runs every half beat, and skips every other iteration of the wave:

```clojure
(let [position-param (params/build-oscillated-param (osc/square-beat) :min 1 :max 2)
      saw-param (params/build-oscillated-param (osc/sawtooth-beat :beat-ratio (/ 2)))
      chase (fx/chase "Gap Saw"
                      [(fx/blank)
                       (afterglow.effects.dimmer/dimmer-effect saw-param
                                                               (show/all-fixtures))]
                      position-param)]
  (show/add-effect! :dimmers chase))
```

You can see the full source in context of how I produced that graph [here](https://github.com/brunchboy/graphterglow/blob/master/src/graphterglow/core.clj#L201-L222), and the namespace declaration at the top of that file can disambiguate the aliases I used in the code snippet if needed.

`position-param` is an oscillated square wave parameter used to switch back and forth between showing the sawtooth wave and suppressing it (showing a [blank effect](https://github.com/brunchboy/afterglow/blob/master/doc/effects.adoc#blank-effects) instead), by indexing which effect in the chase should be active. `saw-param` is a simple sawtooth oscillated parameter that drives the dimmer effect when that element of the chase is active.

An alternate way of doing this would be to use a [step parameter](https://github.com/brunchboy/afterglow/blob/master/doc/parameters.adoc#step-parameters) instead of the square wave, and configure the chase to loop. Or, if we stick with the square wave, we could use a simple [fade](https://github.com/brunchboy/afterglow/blob/master/doc/effects.adoc#fades) instead of the chase, since we are only moving back and forth between two effects.

**Comment by dandaka** [comment] 2015-12-08 07:31
Thank you! 

@brunchboy, since we can't use dynamic parameters in `:min 1 :max 2` and `:beat-ratio (/ 2)`, this generator is still static, right? Or maybe semistatic, since `:min 1 :max 2` could be dynamic? And we are going back to #16.

**Comment by brunchboy** [comment] 2015-12-08 15:11
`:min` and `:max` are arguments to `build-oscillated-param` and can be dynamic. `:beat-ratio` is an argument to `sawtooth-beat` and cannot currently be dynamic, but we may be changing that tonight.

**Comment by brunchboy** [comment] 2015-12-09 15:02
As an aside, the huge refactoring of oscillators that is taking place will probably make it a *lot* easier to create custom waveforms like this. I think I am going to end up with a framework where my code does all the work of interpreting the parameters like `:beat-ratio` and interacting with the metronome, and you can just supply a function which takes as input the current phase (a value from `0` to `1`), and returns what you want the oscillator’s value at that phase to be (also a value from `0` to `1`). So to achieve the alternating sawtooth wave above you could just call the new build-an-oscillator function, passing in a shape function something like:

```clojure
(fn [phase]
  (if (<= phase 0.5)
    (* 2 phase)
    0))
```

**Comment by dandaka** [comment] 2015-12-10 10:24
That is super cool! Will it be possible to use Dynamic parameters inside a shape fn?

**Comment by brunchboy** [comment] 2015-12-10 16:16
That question doesn’t really make sense to me. The shape function is Clojure code that you write yourself, so you can use anything you can imagine, pull in third party libraries, go as wild as you want. :grin: Of course since it needs to run every frame, it should be fast. Once this is out, if you explain what you are trying to do, I can give you an example of how you would code it, if that helps.

And I can report that this approach is working; I have rewritten the sawtooth oscillator based on my new framework, and it is tiny. Tonight I plan to replace the rest of the oscillators, test them, and then merge this into the 0.1.6 snapshot and push it to Clojars. If you want to look at what I have been up to so far, it is in the [redesign-oscillators](https://github.com/brunchboy/afterglow/tree/redesign-oscillators) branch.

**Comment by brunchboy** [comment] 2015-12-11 06:34
Now that the oscillator redesign coding is finished, I can confirm that you can use dynamic parameters inside your `shape-fn`; the new `sawtooth` and `square` implementations take advantage of this. Because dynamic parameters need access to the show, metronome snapshot, and perhaps a lighting head in order to be evaluated, it is more complicated than the simple one-argument example above in such cases, but it is still pretty simple; you can look at the code for those oscillators to see how I do it.

**Comment by brunchboy** [comment] 2015-12-13 03:39
Hopefully the new flexibility of oscillators, their ability to use dynamic parameters, and how easy it now is to create a completely new oscillator ([here](https://github.com/brunchboy/afterglow/blob/master/src/afterglow/effects/oscillators.clj#L317-L320) is all the code it took to implement the built-in triangle wave oscillator in the new design) will enable you to create all the oscillators you need. Let me know if you want sample code for any particular wave forms you dream up, and perhaps we can close this issue?

**Comment by brunchboy** [comment] 2016-03-27 06:43
I am going to close this issue shortly, as part of cleaning up for the next release. First I have to document a bunch of new things, not least the incredible new Push 2 interface that you can see a sneak preview of [here](https://github.com/brunchboy/wayang#capturing-your-interface).

If you have any reason I should not, please let me know.

**Closed** 2017-04-23 20:46 UTC
Labels: enhancement, question
